name: Deploy Laravel migrations to AWS RDS

on:
  push:
    branches: [ "main" ]

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  TEST_SECRET: "I_AM_A_SECRET"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Replace .env credentials
        run: |
          sed -i "s/DB_HOST=.*/DB_HOST=${{ env.DB_HOST }}/g" .env
          sed -i "s/DB_PORT=.*/DB_PORT=${{ env.DB_PORT }}/g" .env
          sed -i "s/DB_DATABASE=.*/DB_DATABASE=${{ env.DB_DATABASE }}/g" .env
          sed -i "s/DB_USERNAME=.*/DB_USERNAME=${{ env.DB_USERNAME }}/g" .env
          sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${{ env.DB_PASSWORD }}/g" .env

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Clear application cache
        run: |
          php artisan cache:clear
          php artisan config:clear
      - name: Migrate database
        run: php artisan migrate


