name: laravel-testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: admin
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Replace .env credentials
        run: |
          sed -i "s/DB_USERNAME=.*/DB_USERNAME=admin/g" .env
          sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=password/g" .env
          sed -i "s/DB_DATABASE=.*/DB_DATABASE=testing/g" .env
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Clear application cache
        run: |
          php artisan cache:clear
          php artisan config:clear
      - name: Migrate database
        run: php artisan migrate
      - name: Execute tests (Unit and Feature tests) via PEST
        run: ./vendor/bin/pest
